#!/bin/sh

### BEGIN INIT INFO
# Provides:        tunnelbroker
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start tunneldigger broker
### END INIT INFO


case "$1" in
  start)
    nohup /usr/bin/python /opt/tunnelbroker/l2tp_broker.py /opt/tunnelbroker/l2tp_broker.cfg > /opt/tunnelbroker/error.log 2>&1 &
    echo "Starting tunnelbroker server "
    ;;
  stop)
    pkill l2tp_broker 
    echo "tunnelbroker has been stopped (didn't double check though)"
    ;;
  *)
    echo "Usage: /etc/init.d/tunnelbroker {start|stop}"
    exit 1
    ;;
esac

exit 0
